package com.notificationengine.authentication.dto;

import jakarta.validation.constraints.NotBlank;
import lombok.Getter;
import lombok.Setter;

/**
 * Request body for the one-time code exchange endpoint.
 *
 * POST /api/v1/auth/google/exchange
 *
 * The code is an opaque UUID generated by GoogleOAuth2SuccessHandler.
 * It must NOT be the application JWT, a Google access token, or any
 * other sensitive credential.
 */
@Getter
@Setter
public class OAuth2ExchangeRequest {

    @NotBlank(message = "Authorization code is required")
    private String code;
}
